# Generated by Django 4.0 on 2022-03-16 16:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='movie',
        ),
    ]
