# Generated by Django 4.0 on 2022-03-22 14:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_latest_upcoming'),
    ]

    operations = [
        migrations.DeleteModel(
            name='latest',
        ),
    ]
