# Generated by Django 4.0 on 2022-03-22 15:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_latest'),
    ]

    operations = [
        migrations.AlterField(
            model_name='latest',
            name='desc',
            field=models.CharField(max_length=500),
        ),
    ]
