# Generated by Django 4.0 on 2022-03-22 15:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0010_alter_latest_desc'),
    ]

    operations = [
        migrations.DeleteModel(
            name='series',
        ),
    ]
