# Generated by Django 4.0 on 2022-03-22 16:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0012_series'),
    ]

    operations = [
        migrations.DeleteModel(
            name='upcoming',
        ),
    ]
