# Generated by Django 4.0 on 2022-03-24 09:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0014_upcoming'),
    ]

    operations = [
        migrations.CreateModel(
            name='chromovies',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('year', models.PositiveIntegerField()),
                ('desc', models.CharField(max_length=500)),
                ('url', models.CharField(max_length=500)),
                ('rating', models.FloatField()),
                ('image1', models.CharField(max_length=500)),
                ('image2', models.CharField(max_length=500)),
                ('image3', models.CharField(max_length=500)),
                ('image4', models.CharField(max_length=500)),
            ],
        ),
    ]
