# Generated by Django 4.0 on 2022-03-31 09:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0020_newlatest'),
    ]

    operations = [
        migrations.DeleteModel(
            name='newlatest',
        ),
    ]
